package main

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

// acmeLEAccount is a persisted ACME (Let's Encrypt) account, scoped to a single
// ACME directory URL. The account private key is stored wrapped, using the same
// envelope scheme as KMS key material.
type acmeLEAccount struct {
	ID           string
	DirectoryURL string
	AccountURI   string
	ContactEmail string
	// AccountKeyDER is the unwrapped PKCS#8 account private key. It is only
	// populated in memory; the store wraps it before persisting.
	AccountKeyDER []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// acmeLECertificate is a publicly-trusted certificate obtained from Let's
// Encrypt. Unlike pcaCertificate it has no local issuing CA; the private key is
// generated by Citadel and stored wrapped so operators can download it.
type acmeLECertificate struct {
	CertID       string
	DirectoryURL string
	Domains      string
	Serial       string
	CertB64      string
	ChainB64     string
	// KeyDER is the unwrapped PKCS#8 leaf private key, populated in memory only.
	KeyDER    []byte
	Status    string
	NotBefore time.Time
	NotAfter  time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

// acmeLEOrder is an in-flight ACME order awaiting manual DNS-01 validation. It
// persists the order URL (and owning account) between the "begin" request that
// returns the TXT records to publish and the "complete" request that finalizes
// issuance once the operator has added them at their DNS provider.
type acmeLEOrder struct {
	OrderID      string
	OrderURL     string
	DirectoryURL string
	Domains      string
	Status       string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

// CreateACMELEOrder persists a pending manual DNS-01 order scoped to the caller.
func (s *dbStore) CreateACMELEOrder(ctx context.Context, order acmeLEOrder) error {
	if order.OrderID == "" {
		order.OrderID = randomHex(12)
	}
	if order.Status == "" {
		order.Status = "pending"
	}
	const q = `
INSERT INTO acme_le_orders (
	order_id, order_url, directory_url, domains, status, account_id, created_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW() + INTERVAL '7 days')
`
	if _, err := s.db.ExecContext(ctx, q,
		order.OrderID, order.OrderURL, order.DirectoryURL, order.Domains, order.Status,
		s.accountForContext(ctx),
	); err != nil {
		return fmt.Errorf("insert acme order: %w", err)
	}
	return nil
}

// GetACMELEOrder loads a pending order owned by the caller's account.
func (s *dbStore) GetACMELEOrder(ctx context.Context, orderID string) (acmeLEOrder, error) {
	const q = `
SELECT order_id, order_url, directory_url, domains, status, created_at, expires_at
FROM acme_le_orders
WHERE order_id = $1 AND account_id = $2
`
	var o acmeLEOrder
	err := s.db.QueryRowContext(ctx, q, orderID, s.accountForContext(ctx)).Scan(
		&o.OrderID, &o.OrderURL, &o.DirectoryURL, &o.Domains, &o.Status, &o.CreatedAt, &o.ExpiresAt,
	)
	if err != nil {
		if err == sql.ErrNoRows {
			return acmeLEOrder{}, fmt.Errorf("acme order not found")
		}
		return acmeLEOrder{}, fmt.Errorf("query acme order: %w", err)
	}
	return o, nil
}

// DeleteACMELEOrder removes a pending order owned by the caller's account.
func (s *dbStore) DeleteACMELEOrder(ctx context.Context, orderID string) error {
	const q = `DELETE FROM acme_le_orders WHERE order_id = $1 AND account_id = $2`
	if _, err := s.db.ExecContext(ctx, q, orderID, s.accountForContext(ctx)); err != nil {
		return fmt.Errorf("delete acme order: %w", err)
	}
	return nil
}

// GetACMELEAccount loads the ACME account for a directory URL. It returns
// sql.ErrNoRows-wrapped error semantics via a not-found message when absent.
func (s *dbStore) GetACMELEAccount(ctx context.Context, directoryURL string) (acmeLEAccount, error) {
	const q = `
SELECT id, directory_url, account_uri, contact_email,
       account_key_wrapped_b64, account_key_nonce_b64, created_at, updated_at
FROM acme_le_accounts
WHERE directory_url = $1
`
	var (
		a          acmeLEAccount
		wrappedB64 string
		nonceB64   string
	)
	err := s.db.QueryRowContext(ctx, q, directoryURL).Scan(
		&a.ID, &a.DirectoryURL, &a.AccountURI, &a.ContactEmail,
		&wrappedB64, &nonceB64, &a.CreatedAt, &a.UpdatedAt,
	)
	if err != nil {
		if err == sql.ErrNoRows {
			return acmeLEAccount{}, fmt.Errorf("acme account not found")
		}
		return acmeLEAccount{}, fmt.Errorf("query acme account: %w", err)
	}
	if wrappedB64 != "" && nonceB64 != "" {
		a.AccountKeyDER, err = s.unwrapKeyMaterial(a.ID, wrappedB64, nonceB64)
		if err != nil {
			return acmeLEAccount{}, fmt.Errorf("unwrap acme account key: %w", err)
		}
	}
	return a, nil
}

// UpsertACMELEAccount inserts or updates the ACME account for its directory URL.
func (s *dbStore) UpsertACMELEAccount(ctx context.Context, account acmeLEAccount) error {
	if account.ID == "" {
		account.ID = randomHex(12)
	}
	wrappedB64, nonceB64, err := s.wrapKeyMaterial(account.ID, account.AccountKeyDER)
	if err != nil {
		return fmt.Errorf("wrap acme account key: %w", err)
	}
	const q = `
INSERT INTO acme_le_accounts (
	id, directory_url, account_uri, contact_email,
	account_key_wrapped_b64, account_key_nonce_b64, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
ON CONFLICT (directory_url) DO UPDATE SET
	id = EXCLUDED.id,
	account_uri = EXCLUDED.account_uri,
	contact_email = EXCLUDED.contact_email,
	account_key_wrapped_b64 = EXCLUDED.account_key_wrapped_b64,
	account_key_nonce_b64 = EXCLUDED.account_key_nonce_b64,
	updated_at = NOW()
`
	if _, err := s.db.ExecContext(ctx, q,
		account.ID, account.DirectoryURL, account.AccountURI, account.ContactEmail,
		wrappedB64, nonceB64,
	); err != nil {
		return fmt.Errorf("upsert acme account: %w", err)
	}
	return nil
}

// CreateACMELECertificate persists a Let's Encrypt certificate and its wrapped
// private key.
func (s *dbStore) CreateACMELECertificate(ctx context.Context, cert acmeLECertificate) error {
	if cert.CertID == "" {
		cert.CertID = randomHex(12)
	}
	wrappedB64, nonceB64, err := s.wrapKeyMaterial(cert.CertID, cert.KeyDER)
	if err != nil {
		return fmt.Errorf("wrap acme cert key: %w", err)
	}
	const q = `
INSERT INTO acme_le_certificates (
	cert_id, directory_url, domains, serial, cert_b64, chain_b64,
	key_wrapped_b64, key_nonce_b64, status, not_before, not_after, created_at, updated_at, account_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), NOW(), $12)
`
	if _, err := s.db.ExecContext(ctx, q,
		cert.CertID, cert.DirectoryURL, cert.Domains, cert.Serial, cert.CertB64, cert.ChainB64,
		wrappedB64, nonceB64, cert.Status, cert.NotBefore, cert.NotAfter, s.accountForContext(ctx),
	); err != nil {
		return fmt.Errorf("insert acme certificate: %w", err)
	}
	return nil
}

// GetACMELECertificate loads a Let's Encrypt certificate, unwrapping its key.
func (s *dbStore) GetACMELECertificate(ctx context.Context, certID string) (acmeLECertificate, error) {
	const q = `
SELECT cert_id, directory_url, domains, serial, cert_b64, chain_b64,
       key_wrapped_b64, key_nonce_b64, status, not_before, not_after, created_at, updated_at
FROM acme_le_certificates
WHERE cert_id = $1
`
	var (
		c          acmeLECertificate
		wrappedB64 string
		nonceB64   string
	)
	err := s.db.QueryRowContext(ctx, q, certID).Scan(
		&c.CertID, &c.DirectoryURL, &c.Domains, &c.Serial, &c.CertB64, &c.ChainB64,
		&wrappedB64, &nonceB64, &c.Status, &c.NotBefore, &c.NotAfter, &c.CreatedAt, &c.UpdatedAt,
	)
	if err != nil {
		if err == sql.ErrNoRows {
			return acmeLECertificate{}, fmt.Errorf("acme certificate not found")
		}
		return acmeLECertificate{}, fmt.Errorf("query acme certificate: %w", err)
	}
	if wrappedB64 != "" && nonceB64 != "" {
		c.KeyDER, err = s.unwrapKeyMaterial(c.CertID, wrappedB64, nonceB64)
		if err != nil {
			return acmeLECertificate{}, fmt.Errorf("unwrap acme cert key: %w", err)
		}
	}
	return c, nil
}

// ListACMELECertificates returns all Let's Encrypt certificates (without key
// material) newest first.
func (s *dbStore) ListACMELECertificates(ctx context.Context) ([]acmeLECertificate, error) {
	const q = `
SELECT cert_id, directory_url, domains, serial, cert_b64, chain_b64,
       status, not_before, not_after, created_at, updated_at
FROM acme_le_certificates
ORDER BY created_at DESC
`
	rows, err := s.db.QueryContext(ctx, q)
	if err != nil {
		return nil, fmt.Errorf("query acme certificates: %w", err)
	}
	defer rows.Close()

	var out []acmeLECertificate
	for rows.Next() {
		var c acmeLECertificate
		if err := rows.Scan(
			&c.CertID, &c.DirectoryURL, &c.Domains, &c.Serial, &c.CertB64, &c.ChainB64,
			&c.Status, &c.NotBefore, &c.NotAfter, &c.CreatedAt, &c.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("scan acme certificate: %w", err)
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// inMemoryStore ACME (Let's Encrypt) implementations are unsupported: the
// feature requires the database-backed wrapping path.
func (s *inMemoryStore) GetACMELEAccount(_ context.Context, _ string) (acmeLEAccount, error) {
	return acmeLEAccount{}, errUnsupported
}

func (s *inMemoryStore) UpsertACMELEAccount(_ context.Context, _ acmeLEAccount) error {
	return errUnsupported
}

func (s *inMemoryStore) CreateACMELECertificate(_ context.Context, _ acmeLECertificate) error {
	return errUnsupported
}

func (s *inMemoryStore) GetACMELECertificate(_ context.Context, _ string) (acmeLECertificate, error) {
	return acmeLECertificate{}, errUnsupported
}

func (s *inMemoryStore) ListACMELECertificates(_ context.Context) ([]acmeLECertificate, error) {
	return nil, errUnsupported
}

func (s *inMemoryStore) CreateACMELEOrder(_ context.Context, _ acmeLEOrder) error {
	return errUnsupported
}

func (s *inMemoryStore) GetACMELEOrder(_ context.Context, _ string) (acmeLEOrder, error) {
	return acmeLEOrder{}, errUnsupported
}

func (s *inMemoryStore) DeleteACMELEOrder(_ context.Context, _ string) error {
	return errUnsupported
}
